### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by Tobe2d** [filliptm/ComfyUI_Fill-Nodes#1]
Can you share the workflow please?

**Comment by filliptm** [comment]
> Can you share the workflow please?

which workflow do you want specifically?

**Comment by Tobe2d** [comment]
If you can, all of them 😁

**Comment by Blogwelt** [comment]
Hey, great stream, I've only just seen it. Is there a way to get your “Basic Workflow Note”? 
I would also buy it on your Patron, I want to get the Loras anyway. But the Basic Workflow is a must :)

**Comment by filliptm** [comment]
> Hey, great stream, I've only just seen it. Is there a way to get your “Basic Workflow Note”? I would also buy it on your Patron, I want to get the Loras anyway. But the Basic Workflow is a must :)

For sure! I'll be adding it as well as many other complicated ones to my patreon! I'm going to be attaching private videos as well to breakdown how to use it and how to optimize it when you start switching models and such

https://www.patreon.com/Machinedelusions

**Comment by Blogwelt** [comment]
paid :) I'm waiting for your workflow User Jadestern

**Comment by filliptm** [comment]
> paid :) I'm waiting for your workflow User Jadestern

thanks for the support! I'm going to be uploading it sometime this next few days, I want to record a quick video on how to use It and how to optimize it when you start changing models and such, stay tuned!
