### ISSUE TITLE
[FEATURE REQUEST] Add TXT as a supported format

### ISSUE THREAD

**Issue by Pojo267** [filliptm/ComfyUI_Fill-Nodes#12]
I'd like to request that you add "TXT" to your supported file formats in nodes that pull images such as Directory Crawl. It works just as well and I always save my images as TXT when they aren't direct outputs and are to be used exclusively within the workflow. Whenever I update your node pack I have to go into the code myself and manually add "TXT" the supported file formats. Thank you!

**Comment by filliptm** [comment]
just so i understand this correctly, you want the ability to load text files from the node?

**Comment by Pojo267** [comment]
Correct. Basically just adding .txt to the supported formats of any nodes that have image loading capabilities like with Directory Crawler in this example.

```
    def crawl_directories(self, directory):
        supported_formats = ["jpg", "jpeg", "png", "bmp", "gif", "txt"]
        image_paths = []

```

**Comment by filliptm** [comment]
would you like the ability to output a string as well? right now the output is just an image so I'm confused on what the txt would output

**Comment by Pojo267** [comment]
Nope! Just the exact same functionality that it currently has. If you change an image to a txt file, most Comfy nodes will still recognize it as an image. For an example, put an image into the input folder and change it to a txt. It will still show up as an option in the Load Image node. I prefer to store certain images at txt files when I only plan to use them for internal functionality.

**Comment by filliptm** [comment]
word, i'll push that update now for you =)

**Comment by Pojo267** [comment]
Thank you! You're awesome! Love your nodes, btw. They've been a game changer for me.
