### ISSUE TITLE
Install  issue: No module named 'librosa'

### ISSUE THREAD

**Issue by dougbtv** [filliptm/ComfyUI_Fill-Nodes#2]
Installed using comfy manager...

```

Traceback (most recent call last):
  File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 4, in <module>
    from .fl_audio_frame_calculator import FL_AudioFrameCalculator
  File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\fl_audio_frame_calculator.py", line 3, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

Cannot import D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes module for custom nodes: No module named 'librosa'
```

```
Import times for custom nodes:
  [...snip...] 
  0.1 seconds (IMPORT FAILED): D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
```

**Comment by filliptm** [comment]
> Installed using comfy manager...
> 
> ```
> 
> Traceback (most recent call last):
>   File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 4, in <module>
>     from .fl_audio_frame_calculator import FL_AudioFrameCalculator
>   File "D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes\fl_audio_frame_calculator.py", line 3, in <module>
>     import librosa
> ModuleNotFoundError: No module named 'librosa'
> 
> Cannot import D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes module for custom nodes: No module named 'librosa'
> ```
> 
> ```
> Import times for custom nodes:
>   [...snip...] 
>   0.1 seconds (IMPORT FAILED): D:\ai-ml\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
> ```

you can solve this by doing 

pip install librosa

in your virtual env for comfyUI

**Comment by dougbtv** [comment]
thanks, I wound up working around it by removing `fl_audio_frame_calculator.py` and the references to it in `__init__.py`

is there a way with comfyui nodes to update the required pip libs so it updates on module install?
