### ISSUE TITLE
Error after latest update - Fill nodes fails to import

### ISSUE THREAD

**Issue by jdc4429** [filliptm/ComfyUI_Fill-Nodes#22]
Getting the following error after updating..

Update custom node 'ComfyUI_Fill-Nodes'
Update: ['https://github.com/filliptm/ComfyUI_Fill-Nodes']
Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin
  stderr: 'fatal: refusing to merge unrelated histories'
CUSTOM NODE PULL: Fail

 0.0 seconds (IMPORT FAILED): C:\inetpub\wwwroot\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes

**Comment by filliptm** [comment]
iv made breaking changes recently, you may have to delete the nodes and re-pull fresh. Iv setup a system now that should never need to be done again once you delete and reinstall this time
