### ISSUE TITLE
Error in New FP16 Upscale Node for some Models

### ISSUE THREAD

**Issue by marhensa** [filliptm/ComfyUI_Fill-Nodes#23]
saw your post on X (https://x.com/Machinedelusion/status/1823856367129780742), that you said

> bounces the precision down to fp16 on upscale models, and the result is almost twice as fast, with virtually 0 fidelity loss in image quality.

It works fine with:
- 4x-UltraSharp.pth
- 4x_RealisticRescaler_100000_G.pth

But some model wont accept this FP16 thing

![image](https://github.com/user-attachments/assets/72479d3b-c4e0-4ac2-873d-5848019c3fe5)

like this model: https://openmodeldb.info/models/4x-FaceUpSharpDAT
(4x-FaceUpSharpDAT)

is there any way it can be supported in FP16 speed, or it's just model limitation?

it's a bummer since FaceUpSharpDAT is the best thing I found to correct paint-brush-y faces of Flux-1 Schnell NF4 model.

![image](https://github.com/user-attachments/assets/d57e980d-c7de-4722-bd09-91434bf3015d)

**Comment by filliptm** [comment]
yeah unfortunately it wont work with all models, nothing I can do about that without actually editing the model itself =/

**Comment by marhensa** [comment]
> yeah unfortunately it wont work with all models, nothing I can do about that without actually editing the model itself =/

okay.. it's not nodes issue then, I'll close this.

thank you for the information...
