### ISSUE TITLE
Warning: Missing Node Types - FL_SDUltimate_Slices

### ISSUE THREAD

**Issue by ThisIsJeron** [filliptm/ComfyUI_Fill-Nodes#26]
Having issue running a workflow due to this missing. I've tried installing via ComfyUI manager and also git cloning and still getting issues. 

Running on a RunPod with an A6000

**Comment by filliptm** [comment]
is the node pack loading? is it just this node that's missing?

**Comment by Yyongming** [comment]
安装了节点，节点管理器也提示安装了， 但就是用不了。

**Comment by tonis110** [comment]
就是这个节点缺失  安装完成搜不到

**Comment by filliptm** [comment]
pushed an update, let me know if you guys are having issues still. If you are, please post the log to let me know

**Comment by tonis110** [comment]
好的，谢谢您的回复。





------------------ Original ------------------
From: Fill ***@***.***&gt;
Date: Wed,Oct 2,2024 3:51 PM
To: filliptm/ComfyUI_Fill-Nodes ***@***.***&gt;
Cc: tonis110 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [filliptm/ComfyUI_Fill-Nodes] Warning: Missing Node Types -FL_SDUltimate_Slices (Issue #26)

**Comment by joel-galleri5** [comment]
> pushed an update, let me know if you guys are having issues still. If you are, please post the log to let me know

hey, i'm using FL_SDUltimate_Slices node in comfyui, it works but when i save my workflow in API format and try to generate images  i'm getting this error "Cannot execute because node FL_SDUltimate_Slices does not exist."

**Comment by steveiswicked** [comment]
Having this issue on recent local install of comfui node works on my original comfyui install but some other stuff is broken there. I'm using comfui manager install missing nodes utility

**Comment by ohmygoobness** [comment]
there are too many nodes, so if any one fails the entire package fails, the Comfyui Manager shows conflict with FL_ImageCaptionSaver (ComfyUI_FL-Trainer) but i had to remove loading FL_DiscordWebhook and FL_ProResVideo from __init__ for it to work.

**Comment by filliptm** [comment]
> there are too many nodes, so if any one fails the entire package fails, the Comfyui Manager shows conflict with FL_ImageCaptionSaver (ComfyUI_FL-Trainer) but i had to remove loading FL_DiscordWebhook and FL_ProResVideo from **init** for it to work.

i replaced the moviepy.editor import with CV2 in both those nodes, let me know if that works for you guys

**Comment by ohmygoobness** [comment]
i don't get errors anymore, looks good.

**Comment by filliptm** [comment]
Fantastic thanks for confirming!

**Comment by LiteSoul** [comment]
I've started using the official ComfyUI Desktop app, and it now gives me the error:
(IMPORT FAILED) due to FL_SDUltimate_Slices inside this node pack.
