### ISSUE TITLE
IMPORT FAILED 

### ISSUE THREAD

**Issue by Maxadox** [filliptm/ComfyUI_Fill-Nodes#29]
Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes module for custom nodes: No module named 'cv2'
D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_fields.py:132: UserWarning: Field "model_name" in HuggingFaceInferenceAPIEmbeddings has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

**Comment by filliptm** [comment]
fixed, try updating

**Comment by Maxadox** [comment]
Thanks professor ! <3
