### ISSUE TITLE
The plugin doesn't work after the update.

### ISSUE THREAD

**Issue by nicegamer12** [filliptm/ComfyUI_Fill-Nodes#38]
Even if you switch the previous version, it will not work
![{6D8E2EF4-A377-4DB8-889E-4A8A2BE385A2}](https://github.com/user-attachments/assets/fad1d812-965a-450d-8e70-34f4bda2d88f)
File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Fill-Nodes\__init__.py", line 62, in <module>
from .nodes.FL_PDFToImage import FL_PDFToImages
File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Fill-Nodes\nodes\FL_PDFToImage.py", line 2, in <module>
import fitz  # PyMuPDF
File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\fitz\__init__.py", line 1, in <module>
from frontend import *
ModuleNotFoundError: No module named 'frontend'
Cannot import D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Fill-Nodes module for custom nodes: No module named 'frontend'
 
 FizzleDorf Custom Nodes: [92mLoaded

**Comment by filliptm** [comment]
try 

pip install fitz

let me know if that helps

**Comment by filliptm** [comment]
iv pushed an update, please let me know if that works!

**Comment by nicegamer12** [comment]
> IV 推送了更新，请告诉我是否有效！

![{08A09475-66B2-4949-A306-181320E9DA0B}](https://github.com/user-attachments/assets/c76e97a4-0103-48b3-bdfa-b44ef5228f0e)
after uninstalling and reinstalling, it can be used！

**Comment by filliptm** [comment]
amazing! thank you for confirming
