### ISSUE TITLE
I have installed it, but I still get an error

### ISSUE THREAD

**Issue by BO1103** [filliptm/ComfyUI_Fill-Nodes#9]
I have installed it, but I still get an error
![微信截图_20240516173730](https://github.com/filliptm/ComfyUI_Fill-Nodes/assets/87166024/8c9cfd56-84e4-402b-bc00-6f697bd8a360)

**Comment by rickyars** [comment]
i'm getting the same error - were you able to figure this out?

**Comment by filliptm** [comment]
scroll back in the log and let me know what error you guys are getting

why its failing to import

**Comment by BO1103** [comment]
> 向后滚动日志并让我知道你们遇到了什么错误
> 
> 为什么导入失败

![image](https://github.com/filliptm/ComfyUI_Fill-Nodes/assets/87166024/c4799c46-d7d6-4c40-a1c0-17abfa7de577)
![image](https://github.com/filliptm/ComfyUI_Fill-Nodes/assets/87166024/ed52b199-5879-4cd1-852b-a9fde9189489)
![image](https://github.com/filliptm/ComfyUI_Fill-Nodes/assets/87166024/34684ad2-fd47-4e98-873c-ee24d388b79c)

I don’t have any logs showing that all dependencies are installed, but I still get an error.

**Comment by rickyars** [comment]
i created a new conda environment and reinstalled everything and it seems to be working. i know that isn't a satisfying solution.

**Comment by roblester** [comment]
I'm also getting this error and have been unable to install this on a RunPod machine. Here is the error I am getting:
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/__init__.py", line 5, in <module>
    from .fl_audio_preview import FL_AudioPreview
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes/fl_audio_preview.py", line 3, in <module>
    import sounddevice as sd
  File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes module for custom nodes: PortAudio library not found

**Comment by filliptm** [comment]
iv disabled my audio nodes for now as some people are having problems

**Comment by filliptm** [comment]
update the latest version from my pack, you may need to delete my custom node folder and redownload it, but it should work now!
